### ISSUE TITLE
Sorry,I can't run the code correctly

### ISSUE THREAD

**Issue by ViaLiu** [ItzikMalkiel/DeepNanoDesign#1]
I can't run the doall.lua,because there is no file 'loadDatasetForInverseFunction.lua'or 'loadDatasetForDirectFunction.lua',could you help me?

**Comment by huanglvtd** [comment]
Have you solved this problem and compeled the train of deep NNs?thank you

**Comment by ViaLiu** [comment]
> Have you solved this problem and compeled the train of deep NNs?thank you

Yes, but  I have just finished some easy work

**Comment by huanglvtd** [comment]
thanks for your answers，are you chinese and can i ask some questions？

**Comment by ViaLiu** [comment]
> thanks for your answers，are you chinese and can i ask some questions？
Of course,you can send emails to me (lq_cug@126.com)

**Comment by Wangweinan16** [comment]
> > thanks for your answers，are you chinese and can i ask some questions？
> > Of course,you can send emails to me ([lq_cug@126.com](mailto:lq_cug@126.com))

Hi! I'm having the same problem, and I am not sure how to read in the data. Can I ask you some specific questions on email? I've sent you one to lq_cug@126.com. Thanks!!

**Comment by ItzikMalkiel** [comment]
Hey,

I've uploaded the dataset loaders. 
Please pull the latest commit.

Best,
Itzik
